### PR TITLE
Document README WIP status.

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by joshwiens** [comment]
@graingert - You will need to sign the CLA before I can merge this.

To trigger the CLA assistant, close / open the pull request

**Comment by TheLarkInn** [comment]
@graingert Would you mind singing the CLA. We have the bot running now. Thank you!

**Comment by graingert** [comment]
The change is small enough to be used under fair use

**Comment by joshwiens** [comment]
@graingert - For reference, the only way to use the CLA consistently across an org with this many contributors & repos is to have a `zero exception` policy in regards to signing it.

Far too much to manage here to introduce a `grey area` like `fair use` into the mix and have to contend with the differing interpretations of what defines fair use.

**Pull request merged**
